apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: Defines how to deploy Heketi
  labels:
    glusterfs: heketi-deployment
  name: heketi
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      glusterfs: heketi-pod
      name: heketi
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        glusterfs: heketi-pod
        name: heketi
      name: heketi
    spec:
      containers:
      - env:
        - name: HEKETI_EXECUTOR
          value: ssh
        - name: HEKETI_SSH_USER
          value: root
        - name: HEKETI_SSH_PORT
        #修改为你的gluster fs所在服务器的ssh端口号
          value: "22"
        - name: HEKETI_SSH_KEYFILE
          value: /root/.ssh/id_rsa
        - name: HEKETI_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: heketi-secret
        image: heketi/heketi:5
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: heketi
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.ssh
          name: heketi-ssh-key
        - mountPath: /var/lib/heketi
          name: heketi-db
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: node2.328ym.com
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - hostPath:
          path: /data/heketi/.ssh
          type: ""
        name: heketi-ssh-key
      - hostPath:
          path: /data/heketi/db
          type: ""
        name: heketi-db
