apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes Heketi Service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"description":"Exposes Heketi Service","tags":"kubernetes,k8s,heketi","traefik.backend.loadbalancer":"wrr","traefik.backend.weight":"10","traefik.enable":"true","traefik.frontend.entryPoints":"http,https","traefik.frontend.rule":"Host:heketi-api.example.com","traefik.tags":"kubernetes"},"labels":{"deploy-heketi":"support","glusterfs":"heketi-service"},"name":"heketi","namespace":"default"},"spec":{"ports":[{"name":"heketi","nodePort":30944,"port":8080,"targetPort":8080}],"selector":{"name":"heketi"},"type":"NodePort"}}
    tags: kubernetes,k8s,heketi
  labels:
    deploy-heketi: support
    glusterfs: heketi-service
  name: heketi
  namespace: default
spec:
  ports:
  - name: heketi
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30944
  type: NodePort
  selector:
    name: heketi
